version: '3'

services:
    
  restapi:
    image: "node:17-alpine3.14"
    container_name: restapi
    depends_on:
      - postgres
    networks:
      - iot
    restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - 5000:5000
    volumes:
      - ./restapi:/home/node/app
    command: "sh start_script.sh"

  reactapp:
    image: "node:17-alpine3.14"
    container_name: reactapp
    depends_on:
      - restapi
    networks:
      - iot
    restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - ./reactapp:/home/node/app
    command: "sh start_script.sh"

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres_database
    expose:
      - 5432
    networks:
      - iot
    volumes: 
      - ./postgres:/var/lib/postgresql/data
      

networks:
  iot: